In [1]:
import pandas as pd
from IPython.display import display

caminho_arquivo = r"../../Arquivos Csv/Base com Escopo definido/pns2019_Filtrada.csv"

df = pd.read_csv(caminho_arquivo)

display(df.head())

,Unnamed: 0,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,...,VDE002,VDE014,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA
0,0,11,1110011,110000016,1,1,2019,6.0,1,1,...,1.0,6.0,2098.0,350.0,2.0,NaN,NaN,NaN,NaN,20210825
1,10,11,1110011,110000016,3,1,2019,8.0,1,1,...,1.0,9.0,4000.0,500.0,3.0,NaN,4.0,NaN,1.0,20210825
2,18,11,1110011,110000016,4,1,2019,1.0,1,1,...,1.0,7.0,324.0,324.0,2.0,NaN,1.0,NaN,NaN,20210825
3,22,11,1110011,110000016,7,1,2019,3.0,1,1,...,1.0,7.0,2998.0,999.0,4.0,NaN,3.0,NaN,NaN,20210825
4,26,11,1110011,110000016,8,1,2019,4.0,1,1,...,NaN,NaN,998.0,250.0,1.0,NaN,NaN,2.0,NaN,20210825

In [2]:
from load import Atributos_Categoricos,Atributos_Numericos

Atributos = Atributos_Categoricos + Atributos_Numericos

df = df[Atributos]

display(df.head())

print(df.shape)

df.to_csv(r'../../Arquivos Csv/Base com Atributos/pns2019_Atributos_Sujo.csv')

,Q074,J01802,J023,J024,Q03001,L01701,L01702,Q092,Q09201,Q09202,...,P023,P02501,P02602,P02801,P029,P03202,A02305,A02306,A02307,C008
0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,1.0,1.0,3.0,...,7.0,0.0,0.0,NaN,5.0,NaN,0.0,2.0,0.0,55.0
1,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,...,0.0,0.0,0.0,7.0,1.0,NaN,1.0,1.0,0.0,45.0
2,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,1.0,0.0,58.0
3,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,...,7.0,1.0,0.0,NaN,NaN,NaN,0.0,8.0,0.0,41.0
4,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,...,2.0,7.0,0.0,2.0,5.0,5.0,0.0,1.0,0.0,38.0

(51830, 113)